package View;

import javafx.fxml.Initializable;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import java.net.URL;
import java.util.ResourceBundle;

public class AboutController implements Initializable {

    public Label TXT;
    public ImageView img;

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        TXT.setWrapText(true);
        TXT.setText("This game is a maze solving game.\n" +
                "The mazes are generated by to two different ways:\n" +
                "randomly or by Prim's algorithm for maze generating.\n" +
                "The player can solve this maze using in one of three\n" +
                "searching algorithm: Breath first algorithm,\n" +
                "depth first algorithm and best first algorithm.");

        img.setImage(new Image(getClass().getResourceAsStream("/Images/logo.png")));
    }
}